# This is a basic workflow to help you get started with Actions

name: Push nuget

# Controls when the action will run. 
on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ master ]
    paths: 
      - 'ModernRonin.ProjectRenamer/release.history'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: run push-package
        shell: pwsh
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        run: .\push-package.ps1
